### ISSUE TITLE
[Feature Request] Prevent non-admins from exporting channels

### ISSUE THREAD

**Issue by icelander** [mattermost/mattermost-plugin-channel-export#27]
Currently the plugin gives every user the ability to run the `/export` slash command in any channel. Customers with sensitive data can't turn this on as it will give users the ability to exfiltrate data. There should be a flag in the plugin settings that prevents non-admins from using the channel export.

**Comment by sCmEcOLJUcL** [comment]
UP!

**Comment by raghavaggarwal2308** [comment]
Fixed with https://github.com/mattermost/mattermost-plugin-channel-export/pull/44

**Comment by wiggin77** [comment]
Fixed via https://github.com/mattermost/mattermost-plugin-channel-export/pull/44
