### ISSUE TITLE
No link present for DM/GM conversation for which the data has been exported in Channel Export DM response.

### ISSUE THREAD

**Issue by AayushChaudhary0001** [mattermost/mattermost-plugin-channel-export#46]
There is no link present for the DM?GM conversation for which the user has exported the data in the response provided by Channel Export bot.

**Steps to reproduce:-**

1. Start a conversation with a single/multiple users as a direct message in Mattermost.
2. Run "/export" slash command.
3. Check the response by Channel Export bot.

For channels, this response contains the channel name as a link, and the user is redirected to the channel by clicking on it. Whereas, for DM/GM, the response consists of some type of ID with it which is not attached to any link.

For channels:-

![image](https://github.com/user-attachments/assets/95915f1b-53a3-4d4d-9e6d-bee0f034d3eb)

For DM/GM:-

![image](https://github.com/user-attachments/assets/bcda988e-c918-4307-87d8-f612eafee080)

**I have two concerns here:-**

- Is it necessary to show that ID in that response for DM/GM or can we replace this with the usernames of the users among whom the conversation is going on?
- Since the user who is a part of that conversation can only export the data, this should be linked so that the user can be redirected(as implemented for channels)

**Comment by raghavaggarwal2308** [comment]
@wiggin77 I think currently we are showing the channel ID for DM/GM in the message. Do you think we should explore if it is possible to show the actual name here?

**Comment by wiggin77** [comment]
Channel names for DM's are in fact the two user ids combined, separated by an underscore.  I can't think of anything better than the channel id to display there.  GM's do not have a real channel name either.
