### ISSUE TITLE
Attachements not working for the data exported.

### ISSUE THREAD

**Issue by AayushChaudhary0001** [mattermost/mattermost-plugin-channel-export#47]
While testing this plugin, it was seen that while the data is exported for any channel, all the attachments are omitted and they are not visible in the csv downloaded.

Even if a post contains some message(text) and an attachment with it, still the attachments are omitted and they are not visible in the csv file downloaded which results into incomplete data exported.

**Comment by raghavaggarwal2308** [comment]
@wiggin77 Is this an expected feature from the plugin. Should we fix this?

**Comment by wiggin77** [comment]
It would appear attachments were not part of the original requirements for this plugin.  We'll leave this capability out until a customer requests it.
